services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "5050:5050"
    volumes:
      - azurite_data:/data
    command: "azurite --blobHost 0.0.0.0 --blobPort 5050"
    environment:
      - NODE_ENV=development

volumes:
  azurite_data: 